paper_id: test
modality: imaging
dataset: mpox_images
model:
  name: logisticregression
  params: { max_iter: 200, n_jobs: -1 }
synth:
  enabled: false
metrics:
  seed: 1337
  threshold_tuning: true
  ci: { enabled: true, B: 1000, alpha: 0.05 }
  auto_doc: true
